<?php

namespace Database\Seeders;

use App\Models\Motif;
use Illuminate\Database\Seeder;

class MotifSeeder extends Seeder
{
    public function run(): void
    {
        $motifs = [
            [
                'name' => 'Batik Parang Barong',
                'description' => 'Motif klasik dengan makna kekuatan dan keteguhan, biasa digunakan dalam upacara adat.',
                'category' => 'Tradisional',
                'location' => 'Yogyakarta',
                'image_url' => '/images/motifs/1.svg',
                'file_path' => '/images/motifs/1.svg',
                'colors' => ['#8B4513', '#D2691E', '#F4A460'],
                'is_featured' => true,
            ],
            [
                'name' => 'Batik Kawung Prabu',
                'description' => 'Simbolisasi kesempurnaan hidup dengan pola geometris yang harmonis dan elegan.',
                'category' => 'Tradisional',
                'location' => 'Solo',
                'image_url' => '/images/motifs/2.svg',
                'file_path' => '/images/motifs/2.svg',
                'colors' => ['#654321', '#A0522D', '#DEB887'],
            ],
            [
                'name' => 'Batik Mega Mendung',
                'description' => 'Motif awan yang melambangkan kesabaran dan ketenangan jiwa.',
                'category' => 'Nusantara',
                'location' => 'Cirebon',
                'image_url' => '/images/motifs/3.svg',
                'file_path' => '/images/motifs/3.svg',
                'colors' => ['#1E40AF', '#3B82F6', '#DBEAFE'],
                'is_featured' => true,
            ],
            [
                'name' => 'Batik Truntum Garuda',
                'description' => 'Motif yang melambangkan cinta kasih yang tumbuh kembali, cocok untuk acara sakral.',
                'category' => 'Tradisional',
                'location' => 'Yogyakarta',
                'image_url' => '/images/motifs/4.svg',
                'file_path' => '/images/motifs/4.svg',
                'colors' => ['#DC2626', '#F59E0B', '#FEF3C7'],
            ],
            [
                'name' => 'Batik Fractal Genesis',
                'description' => 'Perpaduan motif tradisional dengan pola fractal modern yang memukau.',
                'category' => 'Modern',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/5.svg',
                'file_path' => '/images/motifs/5.svg',
                'colors' => ['#7C3AED', '#A855F7', '#E0E7FF'],
            ],
            [
                'name' => 'Batik Sido Luhur',
                'description' => 'Motif yang melambangkan kehormatan dan kemuliaan hidup.',
                'category' => 'Tradisional',
                'location' => 'Solo',
                'image_url' => '/images/motifs/6.svg',
                'file_path' => '/images/motifs/6.svg',
                'colors' => ['#059669', '#10B981', '#D1FAE5'],
            ],
            [
                'name' => 'Batik Urban Jungle',
                'description' => 'Interpretasi modern dari motif flora dengan sentuhan kontemporer yang segar.',
                'category' => 'Kontemporer',
                'location' => 'Bandung',
                'image_url' => '/images/motifs/7.svg',
                'file_path' => '/images/motifs/7.svg',
                'colors' => ['#16A34A', '#22C55E', '#BBFBCE'],
            ],
            [
                'name' => 'Batik Pekalongan Coastal',
                'description' => 'Motif khas pesisir dengan warna-warna cerah yang mencerminkan kehidupan laut.',
                'category' => 'Nusantara',
                'location' => 'Pekalongan',
                'image_url' => '/images/motifs/8.svg',
                'file_path' => '/images/motifs/8.svg',
                'colors' => ['#0EA5E9', '#38BDF8', '#E0F2FE'],
            ],
            [
                'name' => 'Batik Modern Flora',
                'description' => 'Perpaduan motif flora dengan pola yang modern dan segar.',
                'category' => 'Kontemporer',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/9.svg',
                'file_path' => '/images/motifs/9.svg',
                'colors' => ['#F472B6', '#EC4899', '#FF7F9C'],
            ],
            [
                'name' => 'Batik Lereng',
                'description' => 'Motif yang terinspirasi dari lereng gunung dengan pola yang dinamis dan berlapis.',
                'category' => 'Tradisional',
                'location' => 'Malang',
                'image_url' => '/images/motifs/10.svg',
                'file_path' => '/images/motifs/10.svg',
                'colors' => ['#FBBF24', '#F59E0B', '#FEF3C7'],
            ],
            [
                'name' => 'Batik Ombak',
                'description' => 'Motif ombak yang melambangkan ketenangan dan kedamaian, cocok untuk pakaian santai.',
                'category' => 'Nusantara',
                'location' => 'Bali',
                'image_url' => '/images/motifs/11.svg',
                'file_path' => '/images/motifs/11.svg',
                'colors' => ['#2563EB', '#3B82F6', '#DBEAFE'],
            ],
            [
                'name' => 'Batik Geometris',
                'description' => 'Motif geometris yang modern dengan kombinasi warna yang berani.',
                'category' => 'Kontemporer',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/12.svg',
                'file_path' => '/images/motifs/12.svg',
                'colors' => ['#8B5CF6', '#A78BFA', '#E0D7FF'],
            ],
            [
                'name' => 'Batik Bunga Kamboja',
                'description' => 'Motif bunga kamboja yang melambangkan keindahan dan kesegaran, cocok untuk pakaian musim panas.',
                'category' => 'Nusantara',
                'location' => 'Bali',
                'image_url' => '/images/motifs/13.svg',
                'file_path' => '/images/motifs/13.svg',
                'colors' => ['#FBBF24', '#F59E0B', '#FEF3C7'],
            ],
            [
                'name' => 'Batik Anggrek',
                'description' => 'Motif anggrek yang elegan dan anggun, cocok untuk acara formal.',
                'category' => 'Tradisional',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/14.svg',
                'file_path' => '/images/motifs/14.svg',
                'colors' => ['#A78BFA', '#C4B5FD', '#EDE9FE'],
            ],
            [
                'name' => 'Batik Ombak Biru',
                'description' => 'Motif ombak dengan nuansa biru yang menenangkan, cocok untuk pakaian santai.',
                'category' => 'Nusantara',
                'location' => 'Bali',
                'image_url' => '/images/motifs/15.svg',
                'file_path' => '/images/motifs/15.svg',
                'colors' => ['#2563EB', '#3B82F6', '#DBEAFE'],
            ],
            [
                'name' => 'Batik Daun Tropis',
                'description' => 'Motif daun tropis yang segar dan ceria, cocok untuk pakaian musim panas.',
                'category' => 'Kontemporer',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/16.svg',
                'file_path' => '/images/motifs/16.svg',
                'colors' => ['#16A34A', '#22C55E', '#BBFBCE'],
            ],
            [
                'name' => 'Batik Kupu-Kupu',
                'description' => 'Motif kupu-kupu yang indah dan anggun, melambangkan keindahan dan transformasi.',
                'category' => 'Tradisional',
                'location' => 'Yogyakarta',
                'image_url' => '/images/motifs/17.svg',
                'file_path' => '/images/motifs/17.svg',
                'colors' => ['#F472B6', '#EC4899', '#FF7F9C'],
            ],
            [
                'name' => 'Batik Bunga Matahari',
                'description' => 'Motif bunga matahari yang ceria dan penuh semangat, cocok untuk pakaian santai.',
                'category' => 'Nusantara',
                'location' => 'Bali',
                'image_url' => '/images/motifs/18.svg',
                'file_path' => '/images/motifs/18.svg',
                'colors' => ['#FBBF24', '#F59E0B', '#FEF3C7'],
            ],
            [
                'name' => 'Batik Geometris Modern',
                'description' => 'Motif geometris yang modern dengan kombinasi warna yang berani.',
                'category' => 'Kontemporer',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/19.svg',
                'file_path' => '/images/motifs/19.svg',
                'colors' => ['#8B5CF6', '#A78BFA', '#E0D7FF'],
            ],
            [
                'name' => 'Batik Bunga Melati',
                'description' => 'Motif bunga melati yang harum dan anggun, melambangkan kesucian dan keindahan.',
                'category' => 'Tradisional',
                'location' => 'Yogyakarta',
                'image_url' => '/images/motifs/20.svg',
                'file_path' => '/images/motifs/20.svg',
                'colors' => ['#F472B6', '#EC4899', '#FF7F9C'],
            ],
            [
                'name' => 'Batik Ombak Hijau',
                'description' => 'Motif ombak dengan nuansa hijau yang menenangkan, cocok untuk pakaian santai.',
                'category' => 'Nusantara',
                'location' => 'Bali',
                'image_url' => '/images/motifs/21.svg',
                'file_path' => '/images/motifs/21.svg',
                'colors' => ['#16A34A', '#22C55E', '#BBFBCE'],
            ],
            [
                'name' => 'Batik Daun Hutan',
                'description' => 'Motif daun hutan yang segar dan alami, cocok untuk pakaian musim panas.',
                'category' => 'Kontemporer',
                'location' => 'Jakarta',
                'image_url' => '/images/motifs/22.svg',
                'file_path' => '/images/motifs/22.svg',
                'colors' => ['#1E3A8A', '#3B82F6', '#DBEAFE'],
            ],
        ];

        foreach ($motifs as $motif) {
            Motif::create($motif);
        }
    }
}